<a href="https://colab.research.google.com/github/Nawaf-Alorabi/Tw_ML_Predicting_Employee_Burnout_with_Regression/blob/main/project_final_burnout.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Phase One: Data Loading & Core Integration

## Data Source:
https://huggingface.co/datasets/BrotherTony/employee-burnout-turnover-prediction-800k

## Overview:
The primary goal of this phase is to establish a robust and clean foundation for our predictive study. Given the large scale of the HuggingFace synthetic dataset (~850k records), we performed a Strategic Feature Selection to focus only on variables that have a theoretical and empirical impact on employee burnout. This stage ensures our data is structurally sound, normalized in its naming conventions, and prepared for deep exploratory analysis.

## Key Objectives:
- **Selective Data Ingestion:** Streamlining the dataset by importing only **11** critical features (out of **31**) to optimize memory usage and eliminate noise during the training phase.

- **Target Standardization:** Renaming the primary metric from burnout_risk to burnout_score to align with the project's goal of predicting a continuous burnout magnitude.

- **Data Integrity Verification:** Executing a multi step audit including shape, info, and describe to validate data types and understand the statistical range of behavioral metrics.

- **Cleaning & Quality Assurance:** Conducting a rigorous check for missing values (isnull) and duplicated entries to ensure the model isn't trained on biased or redundant information.

In [5]:
import pandas as pd
import numpy as np

In [6]:
# URL Link for dataset
url = "https://huggingface.co/datasets/BrotherTony/employee-burnout-turnover-prediction-800k/resolve/main/synthetic-employee-dataset.json"

In [7]:
# Loading the data
df_all = pd.read_json(url)

In [8]:
df_all.head()

,employee_id,role,job_level,department,tenure_months,salary,performance_score,satisfaction_score,workload_score,team_sentiment,...,goal_achievement_rate,stress_level,burnout_risk,left_company,turnover_reason,risk_factors_summary,turnover_probability_generated,persona_name,role_complexity_score,career_progression_score
0,SYN_00000000,,Mid,Research & Development,169,79704.579059,0.632482,0.623746,0.758117,0.662335,...,0.632482,0.908992,0.866643,False,Not Applicable,Severe Burnout Risk,0.290979,ChangeResistor,0.2,1.000000
1,SYN_00000001,Customer Success Manager,Manager,Research & Development,54,29694.288831,0.538587,0.982556,0.788416,0.934661,...,0.538587,0.363321,0.218996,False,Not Applicable,Low Risk,0.156002,NewEnthusiast,0.2,1.000000
2,SYN_00000002,Administrative Assistant,Entry,HR,1,62208.470185,0.624656,0.767200,0.697617,0.888559,...,0.624656,0.664378,0.541531,True,Personal / Relocation,Low Risk,0.233897,NewEnthusiast,0.2,0.836495
3,SYN_00000003,Senior Manager,Manager,Research & Development,31,236066.567114,0.959320,0.185888,0.493143,0.732189,...,0.959320,1.000000,1.000000,False,Not Applicable,Severe Burnout Risk,0.351682,OverachievingSprinter,0.2,1.000000
4,SYN_00000004,Anonymous Employee,Mid,Research & Development,131,37306.328156,0.677305,0.566706,0.567230,0.817545,...,0.677305,0.723049,0.614825,False,Not Applicable,Low Risk,0.272910,SeasonedExpert,0.2,1.000000

In [9]:
df_all.shape

(849999, 31)

In [10]:
df_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 849999 entries, 0 to 849998
Data columns (total 31 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   employee_id                     849999 non-null  object
 1   role                            849999 non-null  object
 2   job_level                       849999 non-null  object
 3   department                      849999 non-null  object
 4   tenure_months                   849999 non-null  int64
 5   salary                          849999 non-null  float64
 6   performance_score               849999 non-null  float64
 7   satisfaction_score              849999 non-null  float64
 8   workload_score                  849999 non-null  float64
 9   team_sentiment                  849999 non-null  float64
 10  recent_feedback                 849999 non-null  object
 11  communication_patterns          849999 non-null  object
 12  project_completion_rate         849999 non-null  float64
 13  overtime_hours                  849999 non-null  float64
 14  training_participation          849999 non-null  float64
 15  collaboration_score             849999 non-null  float64
 16  technical_skills                849999 non-null  object
 17  soft_skills                     849999 non-null  object
 18  email_sentiment                 849999 non-null  float64
 19  slack_activity                  849999 non-null  float64
 20  meeting_participation           849999 non-null  float64
 21  goal_achievement_rate           849999 non-null  float64
 22  stress_level                    849999 non-null  float64
 23  burnout_risk                    849999 non-null  float64
 24  left_company                    849999 non-null  bool
 25  turnover_reason                 849999 non-null  object
 26  risk_factors_summary            849999 non-null  object
 27  turnover_probability_generated  849999 non-null  float64
 28  persona_name                    849999 non-null  object
 29  role_complexity_score           849999 non-null  float64
 30  career_progression_score        849999 non-null  float64
dtypes: bool(1), float64(18), int64(1), object(11)
memory usage: 195.4+ MB

In [11]:
# chaeck for missing value
df_all.isnull().sum()

employee_id                       0
role                              0
job_level                         0
department                        0
tenure_months                     0
salary                            0
performance_score                 0
satisfaction_score                0
workload_score                    0
team_sentiment                    0
recent_feedback                   0
communication_patterns            0
project_completion_rate           0
overtime_hours                    0
training_participation            0
collaboration_score               0
technical_skills                  0
soft_skills                       0
email_sentiment                   0
slack_activity                    0
meeting_participation             0
goal_achievement_rate             0
stress_level                      0
burnout_risk                      0
left_company                      0
turnover_reason                   0
risk_factors_summary              0
turnover_probability_generated    0
persona_name                      0
role_complexity_score             0
career_progression_score          0
dtype: int64

In [13]:
# Checking for missing duplicates
cols_to_check = [col for col in df_all.columns if df_all[col].apply(lambda x: not isinstance(x, list)).all()]
duplicates_count = df_all.duplicated(subset=cols_to_check).sum()

duplicates_count

np.int64(0)

In [14]:

df_all.describe()

,tenure_months,salary,performance_score,satisfaction_score,workload_score,team_sentiment,project_completion_rate,overtime_hours,training_participation,collaboration_score,email_sentiment,slack_activity,meeting_participation,goal_achievement_rate,stress_level,burnout_risk,turnover_probability_generated,role_complexity_score,career_progression_score
count,849999.000000,849999.000000,849999.000000,849999.000000,849999.000000,849999.000000,849999.000000,849999.000000,849999.000000,849999.000000,849999.000000,849999.000000,849999.000000,849999.000000,849999.000000,849999.000000,849999.000000,849999.000000,849999.000000
mean,70.380999,84563.069751,0.692027,0.581941,0.599490,0.666848,0.595412,3.132903,0.279344,0.473380,0.582392,0.473380,0.473380,0.692027,0.791048,0.735941,0.285327,0.210859,0.841147
std,50.177033,47444.308564,0.183911,0.276268,0.200038,0.178232,0.161173,6.094207,0.221602,0.184961,0.277255,0.184961,0.184961,0.183911,0.264536,0.315756,0.087902,0.085018,0.182216
min,1.000000,27190.569289,0.074113,0.050000,0.006741,0.019774,0.059290,0.000000,0.000079,0.008674,0.042500,0.008674,0.008674,0.074113,0.000000,0.000000,0.131127,0.200000,0.182198
25%,30.000000,41006.776951,0.571340,0.367016,0.455657,0.545729,0.490179,0.000000,0.103691,0.332366,0.367212,0.332366,0.332366,0.571340,0.613005,0.479950,0.227733,0.200000,0.713997
50%,67.000000,78178.525918,0.699235,0.583188,0.613744,0.686320,0.609499,0.000000,0.223123,0.457102,0.583141,0.457102,0.457102,0.699235,0.942151,0.914494,0.299657,0.200000,0.911793
75%,105.000000,116146.639606,0.825585,0.813912,0.756693,0.806540,0.716149,4.161240,0.400716,0.600885,0.811581,0.600885,0.600885,0.825585,1.000000,1.000000,0.335272,0.200000,1.000000
max,357.000000,384330.428656,1.000000,1.000000,0.999615,0.999956,1.000000,73.953574,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.899983,1.000000,1.000000

In [ ]:
# Summary of Categorical (Non-numeric) Columns
df_all.describe(include='object')

#Phese Two: Exploratory Data Analysis (EDA)



## Overview:
The goal of this phase is to visually investigate the patterns and correlations within our optimized dataset. By utilizing statistical plots, we aim to validate our feature engineering decisions and identify the strongest drivers of employee burnout. This stage provides the "Why" behind the numbers before we move to the predictive modeling phase.

## Quick Information (from dataset website):
- Total Records 800,000+
- Departments 38 unique divisions
- Job Roles 300+ distinct positions
- Employee Personas 12 behavioral archetypes
- Features per Record 30+ attributes
- Salary Range 27k -384K

In [ ]:
# Imports

import seaborn as sns
import matplotlib.pyplot as plt

# Improving the appearance of the graphics
sns.set(style="whitegrid")
plt.rcParams["figure.figsize"] = (8, 5)

In [ ]:
plt.figure()
sns.histplot(df_all["burnout_risk"], kde=True)
plt.title("Burnout Risk Distribution")
plt.xlabel("burnout_risk")
plt.ylabel("Count")
plt.show()

> #### A noticeable concentration of higher burnout values suggests that a considerable number of employees may be experiencing elevated work-related strain.




---

In [ ]:
plt.figure()
sns.countplot(x="left_company", data=df_all)
plt.title("Left Company Distribution")
plt.xlabel("left_company")
plt.ylabel("Count")
plt.show()

In [ ]:
numeric_cols = [
    'tenure_months',
    'salary',
    'performance_score',
    'satisfaction_score',
    'workload_score',
    'team_sentiment',
    'project_completion_rate',
    'overtime_hours',
    'training_participation',
    'collaboration_score',
    'email_sentiment',
    'slack_activity',
    'meeting_participation',
    'goal_achievement_rate',
    'stress_level',
    'burnout_risk',
    'role_complexity_score',
    'career_progression_score'
]

In [ ]:
corr = df_all[numeric_cols].corr()

plt.figure(figsize=(14, 8))
sns.heatmap(corr, annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Correlation Heatmap")
plt.show()

>#### The correlation heatmap provides an overall view of how numeric variables relate to each other, helping identify strong positive or negative relationships.

In [ ]:
burnout_features = [
    'tenure_months',
    'salary',
    'performance_score',
    'satisfaction_score',
    'workload_score',
    'team_sentiment',
    'project_completion_rate',
    'overtime_hours',
    'training_participation',
    'collaboration_score',
    'email_sentiment',
    'slack_activity',
    'meeting_participation',
    'goal_achievement_rate',
    'stress_level',
    'role_complexity_score',
    'career_progression_score'
]

burnout_corr = df_all[burnout_features + ['burnout_risk']].corr()['burnout_risk'].sort_values(ascending=False)

print("\nCorrelation with Burnout Risk:")
print(burnout_corr)

print("\nTop Positive Factors Increasing Burnout:")
print(burnout_corr[burnout_corr > 0].sort_values(ascending=False))

print("\nTop Negative Factors Reducing Burnout:")
print(burnout_corr[burnout_corr < 0].sort_values())

In [ ]:
plt.figure()
sns.scatterplot(x="stress_level", y="burnout_risk", data=df_all, alpha=0.3)
plt.title("Stress Level vs Burnout Risk")
plt.show()

>#### Stress level appears to be one of the strongest positive indicators of burnout risk.

In [ ]:
plt.figure()
sns.scatterplot(x="workload_score", y="burnout_risk", data=df_all, alpha=0.3)
plt.title("Workload Score vs Burnout Risk")
plt.show()

>#### A higher workload score is strongly associated with increased burnout risk.

In [ ]:
plt.figure()
sns.scatterplot(x="overtime_hours", y="burnout_risk", data=df_all, alpha=0.3)
plt.title("Overtime Hours vs Burnout Risk")
plt.show()

>#### Employees with more overtime hours tend to have higher burnout risk.

In [ ]:
plt.figure()
sns.scatterplot(x="satisfaction_score", y="burnout_risk", data=df_all, alpha=0.3)
plt.title("Satisfaction Score vs Burnout Risk")
plt.show()

>#### Higher job satisfaction is associated with lower burnout risk.

In [ ]:
plt.figure()
sns.scatterplot(x="team_sentiment", y="burnout_risk", data=df_all, alpha=0.3)
plt.title("Team Sentiment vs Burnout Risk")
plt.show()

>#### A more positive team environment is linked to lower burnout levels.

In [ ]:
df_all["left_company_num"] = df_all["left_company"].astype(int)

turnover_corr = df[burnout_features + ['left_company_num']].corr()['left_company_num'].sort_values(ascending=False)

print("\nCorrelation with Left Company:")
print(turnover_corr)

>#### The correlation heatmap provides an overall view of how numeric variables relate to each other, helping identify strong positive or negative relationships.

In [ ]:
dept_burnout = df_all.groupby("department")["burnout_risk"].mean().sort_values(ascending=False)

plt.figure(figsize=(10, 5))
sns.barplot(x=dept_burnout.index, y=dept_burnout.values)
plt.title("Average Burnout Risk by Department")
plt.xlabel("Department")
plt.ylabel("Average Burnout Risk")
plt.xticks(rotation=45)
plt.show()

>#### Burnout levels vary by department, indicating that workplace pressure may differ depending on the nature of the department.

In [ ]:
plt.figure(figsize=(8, 5))
sns.boxplot(x="job_level", y="burnout_risk", data=df_all)
plt.title("Burnout Risk by Job Level")
plt.show()

>#### Burnout risk differs across job levels, suggesting that seniority or responsibility may influence employee strain.

In [ ]:
important_numeric = [
    'salary',
    'satisfaction_score',
    'workload_score',
    'overtime_hours',
    'stress_level',
    'career_progression_score'
]

In [ ]:
for col in important_numeric:
    plt.figure()
    sns.histplot(df[col], kde=True)
    plt.title(f"{col} Distribution")
    plt.xlabel(col)
    plt.ylabel("Count")
    plt.show()

In [ ]:
for col in important_numeric:
    plt.figure()
    sns.boxplot(x=df[col])
    plt.title(f"{col} Outliers")
    plt.show()

In [ ]:
important_features = [
    'stress_level',
    'workload_score',
    'overtime_hours',
    'satisfaction_score',
    'team_sentiment',
    'project_completion_rate',
    'collaboration_score',
    'goal_achievement_rate',
    'career_progression_score',
    'role_complexity_score',
    'salary',
    'tenure_months',
    'training_participation'
]

print("\nSuggested Important Features for Model Training:")
print(important_features)

In [ ]:
print("\n================ FINAL INSIGHTS ================")
print("1. Higher stress_level, workload_score, and overtime_hours are expected to increase burnout risk.")
print("2. Higher satisfaction_score, team_sentiment, collaboration_score, and career_progression_score are expected to reduce burnout risk.")
print("3. Employees with higher burnout_risk are more likely to leave the company.")
print("4. Department and job_level may show differences in burnout and turnover patterns.")
print("5. The selected important_features can be used later for model training.")

# Phase Three: Data Refinement & Feature Engineering

## Overview:
In this phase, we transition from data discovery to data preparation. Our goal is to refine the dataset by addressing multi-collinearity, encoding categorical variables into a machine-readable format, and scaling numerical features. This ensures that our predictive models can process the information efficiently without bias or data leakage.

## Key Objectives:
- **Feature Pruning (Leakage Prevention):** Eliminating highly correlated features (like **stress_level**) that could artificially inflate model performance.

- **Categorical Encoding:** Converting the role column into numerical values using Target Encoding to manage **300**+ unique job titles without memory overhead.

- **Feature Scaling:** Normalizing numerical ranges using StandardScaler to bring features with different units (**hours** vs. **scores**) into a comparable scale.

### features select

In [ ]:
# Identifying the features selected + the Target (burnout_risk)
selected_columns = [
    'workload_score', 'overtime_hours', 'role_complexity_score',
    'stress_level', 'satisfaction_score', 'team_sentiment',
    'career_progression_score', 'goal_achievement_rate',
    'meeting_participation', 'role', 'burnout_risk'
]

In [ ]:
#Filtering the data to only the selected columns
BO_data = df_all[selected_columns].copy

In [ ]:
#Renaming burnout_risk to burnout_score
BO_data.rename(columns={'burnout_risk': 'burnout_score'}, inplace=True)

In [ ]:
# 1. Dropping High-Leakage Features
BO_data.drop(columns=['stress_level'], inplace=True)

In [ ]:
BO_data.head()

In [ ]:
# 2. Handling Categorical Variables (Target Encoding for 'role')
# Since 'role' has 300+ unique values, One-Hot Encoding is too heavy.
# We use the mean of the target for each role.
role_target_mean = BO_data.groupby('role')['burnout_score'].mean()
BO_data['role_encoded'] = BO_data['role'].map(role_target_mean)

In [ ]:
# Drop the original categorical 'role' column
BO_data.drop(columns=['role'], inplace=True)

### Feature Engineering:

In [ ]:
# Question: How does job difficulty and Workeload combine to create mental strain?
# Pressure Index: High score indicates a high risk of exhaustion due to complex tasks plus heavy workload
BO_data['pressure_index'] = BO_data['role_complexity_score'] * BO_data['workload_score']

In [ ]:
# Question: What is the relationship between overtime hours and  satisfaction?
# Burnout Propensity: High score means the employee is working overtime but has low satisfaction
BO_data['burnout_propensity'] = BO_data['overtime_hours'] / (BO_data['satisfaction_score'] + 0.1)

In [ ]:
# Question: Is the employee extra effort actually leading to results?
# Effort Efficiency: Low score indicates that overtime hours are NOT translating into goal achievement.
BO_data['effort_efficiency'] = BO_data['goal_achievement_rate'] / (BO_data['overtime_hours'] + 1)

In [ ]:
# High workload with low satisfaction leads to burnout
BO_data['burnout_pressure'] = BO_data['workload_score'] / (BO_data['satisfaction_score'] + 0.1)

In [ ]:
# Question: Does the team environment protect the employee from work pressure?
BO_data['culture_shield'] = BO_data['team_sentiment'] * BO_data['satisfaction_score']

### Final Dataset Structuring:

In [ ]:
# Delete outliers
BO_data.replace([np.inf, -np.inf], np.nan, inplace=True)
BO_data.dropna(inplace=True)

In [ ]:
# Reordering columns to place the Target (burnout_score) at the very end.
cols = [c for c in BO_data.columns if c != 'burnout_score'] + ['burnout_score']
BO_data = BO_data[cols]

In [ ]:
BO_data.head()

In [ ]:
new_features_corr = BO_data[['pressure_index', 'burnout_propensity', 'culture_shield', 'burnout_score']].corr()
sns.heatmap(new_features_corr, annot=True, cmap='coolwarm')
plt.title("Validation of New Engineered Features")
plt.show()

###Insight:

- A positive correlation of 0.26 validates that employees who endure high overtime with minimal emotional returns are significantly more susceptible to burnout.

- With a strong negative correlation of -0.57, the Culture Shield acts as the most powerful defense mechanism, proving that high team sentiment and job satisfaction drastically neutralize burnout risk.

- The unexpected negative correlation of -0.25 suggests that high-complexity roles in this dataset may benefit from superior support systems or higher engagement, mitigating strain compared to high-volume routine tasks.

#Phase Four: Model training, Selection and Evaluation

## Overview:


## Key Objectives:

### Baseline model: Linear Regression

In [ ]:
# Abrar

### Model 1: Random Forest

In [ ]:
# Abrar

### Model 2: XGBoost

In [ ]:
# Abdulmajeed

### Model 3: LightGBM

In [ ]:
# Abdulmajeed